gitGraph
   commit id: "a1b2c3" tag: "v1.0"
   commit id: "d4e5f6"
   branch develop
   commit id: "dev1" tag: "dev-start"
   commit id: "dev2"
   commit id: "dev3"
   checkout main
   commit id: "g7h8i9" tag: "merge"
   commit id: "j1k2l3"