flowchart TD
    A[UML<br>Diagrams]
    A --> B1[Structure<br>Diagrams]
    A --> B2[Behavior<br>Diagrams]

    %% Structure Diagrams
    B1 --> S1[Class<br>Diagram]
    B1 --> S2[Component<br>Diagram]
    B1 --> S3[Composite<br>Structure<br>Diagram]
    B1 --> S4[Deployment<br>Diagram]
    B1 --> S5[Object<br>Diagram]
    B1 --> S6[Package<br>Diagram]
    B1 --> S7[Profile<br>Diagram]

    %% Behavior Diagrams
    B2 --> B21[Use Case<br>Diagram]
    B2 --> B22[Activity<br>Diagram]
    B2 --> B23[State Machine<br>Diagram]
    B2 --> B24[Sequence<br>Diagram]
    B2 --> B25[Communication<br>Diagram]
    B2 --> B26[Interaction<br>Overview<br>Diagram]
    B2 --> B27[Timing<br>Diagram]
